#include "script.h"
#include <string>

#pragma warning(disable : 4244 4305) // double <-> float conversions

// FROM SHOW COORDS MOD
void draw_text(char *text, float x, float y, float scale) {
	UI::SET_TEXT_FONT(0);
	UI::SET_TEXT_SCALE(scale, scale);
	UI::SET_TEXT_COLOUR(0, 255, 0, 245);
	UI::SET_TEXT_WRAP(0.0, 1.0);
	UI::SET_TEXT_CENTRE(0);
	UI::SET_TEXT_DROPSHADOW(2, 2, 0, 0, 0);
	UI::SET_TEXT_EDGE(1, 0, 0, 0, 205);
	UI::_SET_TEXT_ENTRY("STRING");
	UI::_ADD_TEXT_COMPONENT_STRING(text);
	UI::_DRAW_TEXT(x, y);
}

/* REMOVED VEHICLES:
	BOATTRAILER BUS ARMYTANKER ARMYTRAILER
	ARMYTRAILER2 SUNTRAP COACH AIRBUS
	AIRTUG BARRACKS BARRACKS2 BENSON
	BIFF BOXVILLE BOXVILLE2 BOXVILLE3
	BULLDOZER BLIMP CABLECAR CAMPER
	CUTTER DUMP RUBBLE DOCKTUG
	FORKLIFT HAULER HANDLER JOURNEY
	MIXER MIXER2 MOWER MULE
	MULE2 PACKER PBUS PHANTOM
	POUNDER PROPTRAILER RENTALBUS RHINO
	RIOT RIPLEY SCRAP STOCKADE
	STOCKADE3 TACO TRASH TRACTOR
	TRACTOR2 GRAINTRAILER BALETRAILER TIPTRUCK
	TIPTRUCK2 UTILLITRUCK UTILLITRUCK2 UTILLITRUCK3
	SCORCHER TRIBIKE TRIBIKE2 TRIBIKE3
	FIXTER CRUISER BMX FAGGIO2
	ANNIHILATOR BUZZARD BUZZARD2 CARGOBOB
	CARGOBOB2 CARGOBOB3 SKYLIFT POLMAV
	MAVERICK FROGGER FROGGER2 CUBAN800
	DUSTER STUNT MAMMATUS JET
	SHAMAL LUXOR TITAN LAZER
	CARGOPLANE SQUALO MARQUIS DINGHY
	DINGHY2 JETMAX PREDATOR TROPIC
	SEASHARK SEASHARK2 SUBMERSIBLE TRAILERS 
	TRAILERS2 TRAILERS3 TVTRAILER RAKETRAILER 
	TANKER TRAILERLOGS TR2 TR3
	TR4 TRFLAT TRAILERSMALL VELUM
	SPEEDER VESTRA MILJET DODO
	SUBMERSIBLE2 HYDRA SAVAGE VALKYRIE
	VELUM2 SWIFT2 LUXOR2 BESRA
	SWIFT BLIMP2 TORO CARGOBOB4
	DINGHY4 SEASHARK3 SPEEDER2 SUPERVOLITO
	SUPERVOLITO2 TORO2 TROPIC2 VALKYRIE2 
*/
LPCSTR vehicleModels[268] = {
	"NINEF", "NINEF2", "BLISTA", "ASEA", "ASEA2", "ASTEROPE", "AMBULANCE", "BALLER", "BALLER2",
	"BJXL", "BANSHEE", "BFINJECTION", "BLAZER", "BLAZER2", "BLAZER3", "BISON", "BISON2",
	"BISON3", "BOBCATXL", "BODHI2", "BUCCANEER", "BUFFALO", "BUFFALO2",
	"BULLET", "BURRITO", "BURRITO2", "BURRITO3", "BURRITO4", "BURRITO5", "CAVALCADE", "CAVALCADE2", "POLICET",
	"GBURRITO", "CADDY", "CADDY2", "CARBONIZZARE", "CHEETAH", "COMET2", "COGCABRIO", "COQUETTE",
	"GRESLEY", "DILETTANTE", "DILETTANTE2", "DUNE", "DUNE2", "HOTKNIFE", "DLOADER", "DUBSTA", "DUBSTA2",
	"DOMINATOR", "EMPEROR", "EMPEROR2", "EMPEROR3", "ENTITYXF", "EXEMPLAR", "ELEGY2",
	"F620", "FBI", "FBI2", "FELON", "FELON2", "FELTZER2", "FIRETRUK", "FQ2",
	"FUSILADE", "FUGITIVE", "FUTO", "GRANGER", "GAUNTLET", "HABANERO", "INFERNUS", "INGOT",
	"INTRUDER", "ISSI2", "JACKAL", "JB700", "KHAMELION", "LANDSTALKER", "LGUARD", "MANANA", "MESA",
	"MESA2", "MESA3", "CRUSADER", "MINIVAN", "MONROE",
	"ORACLE", "ORACLE2", "PATRIOT", "PENUMBRA", "PEYOTE", "PHOENIX", "PICADOR",
	"POLICE", "POLICE4", "POLICE2", "POLICE3", "POLICEOLD1", "POLICEOLD2", "PONY", "PONY2", "PRAIRIE",
	"PRANGER", "PREMIER", "PRIMO", "RANCHERXL", "RANCHERXL2", "RAPIDGT", "RAPIDGT2", "RADI", "RATLOADER",
	"REBEL", "REGINA", "REBEL2", "RUINER", "RUMPO", "RUMPO2",
	"ROCOTO", "ROMERO", "SABREGT", "SADLER", "SADLER2", "SANDKING", "SANDKING2", "SCHAFTER2", "SCHWARZER",
	"SEMINOLE", "SENTINEL", "SENTINEL2", "ZION", "ZION2", "SERRANO", "SHERIFF", "SHERIFF2", "SPEEDO", "SPEEDO2",
	"STANIER", "STINGER", "STINGERGT", "STRATUM", "SULTAN", "SUPERD", "SURANO", "SURFER",
	"SURFER2", "SURGE", "TAILGATER", "TAXI", "TORNADO", "TORNADO2", "TORNADO3", "TORNADO4", "TOWTRUCK2",
	"VOODOO2", "WASHINGTON", "STRETCH", "YOUGA", "ZTYPE", "SANCHEZ", "SANCHEZ2", "POLICEB", "AKUMA", "CARBONRS",
	"BAGGER", "BATI", "BATI2", "RUFFIAN", "DAEMON", "DOUBLE", "PCJ", "VADER", "VIGERO", "HEXER", "NEMESIS",
	"ADDER", "VOLTIC", "VACCA", "BIFTA",
	"PARADISE", "KALAHARI", "JESTER", "TURISMOR", "ALPHA", "HUNTLEY", "THRUST", "MASSACRO",
	"MASSACRO2", "ZENTORNO", "BLADE", "GLENDALE", "PANTO", "PIGALLE", "WARRENER", "RHAPSODY", "DUBSTA3", "MONSTER",
	"SOVEREIGN", "INNOVATION", "HAKUCHOU", "FUROREGT", "COQUETTE2", "BTYPE", "BUFFALO3", "DOMINATOR2", "GAUNTLET2",
	"MARSHALL", "DUKES", "DUKES2", "STALION", "STALION2", "BLISTA2", "BLISTA3",
	"INSURGENT", "INSURGENT2", "TECHNICAL", "KURUMA", "KURUMA2", "JESTER2", "CASCO",
	"GUARDIAN", "ENDURO", "LECTRO", "SLAMVAN", "SLAMVAN2", "RATLOADER2", "FELTZER3", "OSIRIS",
	"VIRGO", "WINDSOR", "BESRA", "VINDICATOR", "T20", "COQUETTE3", "CHINO",
	"BRAWLER", "BUCCANEER2", "CHINO2", "FACTION", "FACTION2", "MOONBEAM", "MOONBEAM2", "PRIMO2", "VOODOO", "LURCHER",
	"BTYPE2", "BALLER3", "BALLER4", "BALLER5", "BALLER6", "COG55", "COG552", "COGNOSCENTI", "COGNOSCENTI2",
	"LIMO2", "MAMBA", "NIGHTSHADE", "SCHAFTER3", "SCHAFTER4", "SCHAFTER5", "SCHAFTER6",
	"VERLIERER2", "TAMPA", "BANSHEE2", "SULTANRS", "BTYPE3"
};

void set_player_current_vehicle(LPCSTR modelName) {
	DWORD model = GAMEPLAY::GET_HASH_KEY((char *)modelName);
	if (STREAMING::IS_MODEL_IN_CDIMAGE(model) && STREAMING::IS_MODEL_A_VEHICLE(model)) {
		STREAMING::REQUEST_MODEL(model);
		while (!STREAMING::HAS_MODEL_LOADED(model)) WAIT(0);

		Vector3 coords = ENTITY::GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(PLAYER::PLAYER_PED_ID(), 0.0, 5.0, 0.0);
		Vehicle veh = VEHICLE::CREATE_VEHICLE(model, coords.x, coords.y, coords.z, 0.0, 1, 1);
		VEHICLE::SET_VEHICLE_ON_GROUND_PROPERLY(veh);

		float prevVehicleSpeed = 0.0f;

		if (PED::IS_PED_IN_ANY_VEHICLE(PLAYER::PLAYER_PED_ID(), 0)) {
			Vehicle currentVehicle = PED::GET_VEHICLE_PED_IS_USING(PLAYER::PLAYER_PED_ID());
			prevVehicleSpeed = ENTITY::GET_ENTITY_SPEED(currentVehicle);

			ENTITY::SET_ENTITY_AS_MISSION_ENTITY(currentVehicle, true, true);
			VEHICLE::DELETE_VEHICLE(&currentVehicle);
		}

		ENTITY::SET_ENTITY_HEADING(veh, ENTITY::GET_ENTITY_HEADING(PLAYER::PLAYER_PED_ID()));
		VEHICLE::SET_VEHICLE_ENGINE_ON(veh, true, true, false);
		if (prevVehicleSpeed > 0.0f) {
			VEHICLE::SET_VEHICLE_FORWARD_SPEED(veh, prevVehicleSpeed);
		}
		AUDIO::SET_VEHICLE_RADIO_ENABLED(veh, false);
		PED::SET_PED_INTO_VEHICLE(PLAYER::PLAYER_PED_ID(), veh, -1);

		WAIT(0);
		STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(model);
		ENTITY::SET_VEHICLE_AS_NO_LONGER_NEEDED(&veh);
	}
}

void main() {
	//bool widescreen = GRAPHICS::GET_IS_WIDESCREEN();

	bool randomCarsEnabled = false;

	Any cumulativeStuntJumpsCompleted = GAMEPLAY::_0x6856EC3D35C81EA4();
	int previousRandVehicleIndex = -1;

	while (true) {
		// playerPed = PLAYER::PLAYER_PED_ID();
		//widescreen = GRAPHICS::GET_IS_WIDESCREEN();

		/*char statName[16] = "USJS_COMPLETED";
		Hash statHash = GAMEPLAY::GET_HASH_KEY(statName);

		int stuntJumpsCompleted;
		STATS::STAT_GET_INT(statHash, &stuntJumpsCompleted, -1);*/

		/*bool stuntJumpInProgress = GAMEPLAY::IS_STUNT_JUMP_IN_PROGRESS();
		bool stuntJumpResultsOpen = GAMEPLAY::_0x2272B0A1343129F4();*/

		//Any stuntJumpsCompleted = GAMEPLAY::_0x996DD1E1E02F1008();
		Any cmJumps = GAMEPLAY::_0x6856EC3D35C81EA4();

		if (cmJumps > cumulativeStuntJumpsCompleted) {

			if (randomCarsEnabled) {
				int randVehicleIndex = (rand() % 268);
				while (randVehicleIndex == previousRandVehicleIndex) {
					randVehicleIndex = (rand() % 268);
				}
				LPCSTR randVehicleModel = vehicleModels[randVehicleIndex];

				set_player_current_vehicle(randVehicleModel);
				previousRandVehicleIndex = randVehicleIndex;
			}
			else {
				randomCarsEnabled = true;
			}
			cumulativeStuntJumpsCompleted = cmJumps;
		}

		//char coords[128];

		//sprintf_s(coords, "RANDOM CARS ENABLED: %i", randomCarsEnabled);
		//sprintf_s(coords, "STUNT IN PROGRESS: %i, STUNT RESULTS OPEN: %i, STUNT JUMPS COMPLETED: %lu (%lu)", stuntJumpInProgress, stuntJumpResultsOpen, stuntJumpsCompleted, cumulativeStuntJumpsCompleted);
		//widescreen ? draw_text(coords, 0.205 - 0.03, 0.9, 0.5) : draw_text(coords, 0.205, 0.9, 0.5);

		WAIT(0);
	}
}

void ScriptMain() {
	srand(GetTickCount());
	main();
}
